const LETTER_DELETE = 'LETTER_DELETE';
const LETTER_DELETE_ERROR = 'LETTER_DELETE_ERROR';
const LETTER_DELETE_SUCCESS = 'LETTER_DELETE_SUCCESS';

const LETTER_SELECT = 'LETTER_SELECT';
const LETTER_SELECT_ERROR = 'LETTER_SELECT_ERROR';
const LETTER_SELECT_SUCCESS = 'LETTER_SELECT_SUCCESS';

const LETTER_FAVORITE = 'LETTER_FAVORITE';
const LETTER_FAVORITE_ERROR = 'LETTER_FAVORITE_ERROR';
const LETTER_FAVORITE_SUCCESS = 'LETTER_FAVORITE_SUCCESS';

const LETTER_SEND = 'LETTER_SEND';
const LETTER_SEND_ERROR = 'LETTER_SEND_ERROR';
const LETTER_SEND_SUCCESS = 'LETTER_SEND_SUCCESS';

export {
  LETTER_DELETE,
  LETTER_DELETE_ERROR,
  LETTER_DELETE_SUCCESS,

  LETTER_SELECT,
  LETTER_SELECT_ERROR,
  LETTER_SELECT_SUCCESS,

  LETTER_FAVORITE,
  LETTER_FAVORITE_ERROR,
  LETTER_FAVORITE_SUCCESS,

  LETTER_SEND,
  LETTER_SEND_ERROR,
  LETTER_SEND_SUCCESS
}